# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    volumes:
      - .:/app
    ports:
      - "8008:8000"


  db:
        image: postgis/postgis:17-3.5
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        ports:
          - "5433:5432"
        env_file:
          - .env.local
volumes:
  postgres_data: