version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    expose:
        - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgis/postgis:17-3.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
#    env_file:
#      - ./.env.prod.db

  nginx:
      build: ./nginx
      ports:
        - "1337:80"
      depends_on:
        - web

volumes:
  postgres_data: