version: '3.8'

services:
  web:
    build: .
    command: python3 -m debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --reload --host 0.0.0.0 --port 8000

    volumes:
      - .:/app
    ports:
      - "8008:8000"
      - "5678:5678"
      
    env_file:
      - .env.local


  db:
        image: postgis/postgis:17-3.5
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        ports:
          - "5433:5432"
        env_file:
          - .env.local
volumes:
  postgres_data: